<a href="https://colab.research.google.com/github/KIMCAT33/Tensorflow-2.0/blob/master/TensorFlow_2_0_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


## Static graph (TensorFlow 1.x) vs Eager execution (TensorFlow 2.0)

![alt text](https://www.tensorflow.org/images/tensors_flowing.gif)
*Image take from: https://www.tensorflow.org/guide/graphs*


## TensorFlow 1.X




### Installing TensorFlow 1.X



In [3]:
!pip install tensorflow-gpu==1.13.1

In [0]:
import tensorflow as tf

In [5]:
tf.__version__

'1.13.1'

### Variables and constants in TF 1.x

#### Variables

In [6]:
#tf 1.x에서  normal Variable을 정의한다.
variable = tf.Variable([[30, 20], [10, 45]])

Instructions for updating:
Colocations handled automatically by placer.


In [7]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32_ref>

In [8]:
#변수의 shape를 출력한다. 
variable.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [9]:
 # 다른 tf.Tensor 객체에 덧셈 연산을 수행한다. 
variable + 2

<tf.Tensor 'add:0' shape=(2, 2) dtype=int32>

In [10]:
 # session을 초기화하지 않으면 그 값(variable/Tensor)에 접근할 수 없다. 
variable.eval()

ValueError: ignored

In [12]:
 # 변수를 슬라이싱할 수 있으나 여전히 그 값에 접근할 수는 없다. 
variable[:1, :1] # (~1,~1)까지

<tf.Tensor 'strided_slice_1:0' shape=(1, 1) dtype=int32>

#### Getting values from variables

In [0]:
#Session을 초기화한다.
session = tf.Session()

In [0]:
#세션을 위해 모든 variable을 초기화한다. 
session.run(tf.global_variables_initializer())

In [17]:
# 값에 접근하기 위해서 제공된 session의 환경 안에서 eval 메서드를 실행한다.

variable.eval(session)

array([[30, 20],
       [10, 45]], dtype=int32)

#### Constants/Tensors

In [0]:
#Tensorflow constant matrix 정의
tensor = tf.constant([[23, 4], [32, 51]])

In [19]:
tensor

<tf.Tensor 'Const:0' shape=(2, 2) dtype=int32>

In [20]:
#여전히 session을 초기화하지 않고 그 값에 접근할 수 없다.
tensor.eval()

ValueError: ignored

#### Getting values from constants

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
 # 텐서 그래프/세션으로부터 텐서를 fatch합니다.
tensor_value = session.run(tensor)

In [25]:
tensor_value

array([[23,  4],
       [32, 51]], dtype=int32)

## TensorFlow 2.0

### Installing TensorFlow 2.0

In [26]:
!pip install tensorflow-gpu==2.0.0-alpha0

     |████████████████████████████████| 332.1MB 56kB/s 
     |████████████████████████████████| 3.0MB 33.8MB/s 
     |████████████████████████████████| 419kB 40.4MB/s 
  Found existing installation: tensorflow-gpu 1.13.1
    Uninstalling tensorflow-gpu-1.13.1:
      Successfully uninstalled tensorflow-gpu-1.13.1


In [0]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.0.0-alpha0'

### Constants/Tensors

In [0]:
# TensorFlow 2.0 에서 constant를 정의한다.
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [4]:
# TensorFlow 1.x와 다르게 바로 constant에 접근 가능하다.
tensor_20

<tf.Tensor: id=0, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [5]:
#tensor의 shape를 출력 shape() 안쓴다. 
tensor_20.shape

TensorShape([2, 2])

### Getting values from constants

In [7]:
# Tensorflow constant를 session 없이 numpy 형식으로 얻을 수 있다.
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [0]:
# numpy matrix를 TensorFlow tensor 형태로 변환도 가능하다.
numpy_tensor = np.array([[23,  4], [32, 51]])

In [0]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [11]:
tensor_from_numpy

<tf.Tensor: id=4, shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### Operations with constants/tensors

In [12]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: id=6, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#### Addition between scalar and tensor

In [13]:
tensor + 2

<tf.Tensor: id=9, shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

#### Multiplication between scalar and tensor

In [14]:
tensor * 5

<tf.Tensor: id=12, shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

#### Using Numpy functions on TensorFlow tensors

In [15]:
#  tensorflow tensor 객체의 값을 모두 제곱
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [16]:
# tensorflow tensor 객체 모든 값의 제곱근
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

#### Dot product between two tensors

In [32]:
tensor = tf.constant([[1,2],[3,4]])
tensor_20 = tf.constant([[1,2],[3,4]])
print(tensor.numpy())
print(tensor_20.numpy())
np.dot(tensor, tensor_20)  # 행렬의 multiplication 메서드 

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


array([[ 7, 10],
       [15, 22]], dtype=int32)

### Operations with variables

In [25]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

#### Getting raw value from the variable

In [26]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

#### Changing specific value in the TensorFlow variable

In [33]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [35]:
tf2_variable.numpy()

array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)

### Strings in TensorFlow 2.0

In [36]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=101, shape=(), dtype=string, numpy=b'TensorFlow'>

#### Simple string operations

In [39]:
tf.strings.length(tf_string).numpy()  # string 길이 출력

10

In [41]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=120, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119], dtype=int32)>

### Storing arrays of strings

In [0]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [46]:
# TF string array 반복문
for string in tf_string_array:
  print(string.numpy())

b'TensorFlow'
b'Deep Learning'
b'AI'


### Handling Devices in TensorFlow 2.0

#### CPU

In [0]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [48]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'

#### GPU

In [0]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)